name: Deploy FastAPI to Azure Web App

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Adjust if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive application files
      run: zip -r app.zip . -x "*.git*"  # Exclude .git files

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        slot-name: "Production"
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: app.zip
